### ISSUE TITLE
server segfaults on remote computer sending information

### ISSUE THREAD

**Issue by itdaniher** [nonolith/connect#1]
http://imgur.com/JyHD3

To reproduce:

Computer a: sudo ./server

Computer b: python dataServerClient.py -m "ws.dev.v = 1"

When dataServerClient.py:135 has been changed to point at the proper IP/hostname

**Comment by itdaniher** [comment]
Edit: It's not specific to remote computers, previously provided reproduce instructions will segfault regardless of machine of execution.

**Comment by itdaniher** [comment]
OS: Ubuntu 10.04, compiled with exclusively up-to-date libs.

**Comment by kevinmehall** [comment]
Your library is asking for a -1s sample, which is interpreted as 2^32s. 

e59d484 adds a check so the server won't crash if malloc() fails. It should probably also give a sane error if you do something stupid.
