### ISSUE TITLE
Compile error on Raspberry Pi 2

### ISSUE THREAD

**Issue by Kollensperger** [nonolith/connect#6]
Hi, 
I get an error trying to compile via scons on debian on a raspberry pi 2

I installed the following packages via apt-get:
debhelper, scons, libusb-1.0-0-dev, libudev-dev, libboost-all-dev, libasio-dev

then run scons -j5

here is some of the output with the typical error:

g++ -o url.o -c -Wall -g -O3 -Ilibusb -Iwebsocketpp/src -shared -g -O3 -fstack-protector-all -D_FORTIFY_SOURCE=2 url.cpp
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See file:///usr/share/doc/gcc-4.6/README.Bugs for instructions.
scons: **\* [websocketpp/src/websocket_server_session.o] Error 4
/tmp/cc0Xbjje.s: Assembler messages:
/tmp/cc0Xbjje.s:2071: Warning: swp{b} use is deprecated for ARMv6 and ARMv7
/tmp/cc0Xbjje.s:2100: Warning: swp{b} use is deprecated for ARMv6 and ARMv7
/tmp/cc0Xbjje.s:2136: Warning: swp{b} use is deprecated for ARMv6 and ARMv7

etc before it says

scons: building terminated because of errors.

Any ideas how i can get this to run?

**Comment by kevinmehall** [comment]
I've seen the error `g++: internal compiler error: Killed (program cc1plus)` before when the system ran out of memory and the kernel killed one of the compiler processes. Check your kernel logs with `dmesg` to see if this is the case, and try omitting the `-j5` argument to avoid running multiple compiler processes in parallel.

**Comment by Kollensperger** [comment]
Thanks Kevin, that helped, I am now getting much further.

Apparently the -mt suffix has been removed from -lboost_system -lboost_regex -lboost_thread.
(http://askubuntu.com/questions/486006/cannot-find-boost-thread-mt-library)
so I removed the line boostlibs = [i+'-mt' for i in boostlibs] from the SConstruct file.

nonolith-connect now compiles, and the nonolith connect webpage  states that I have the correct version, 1.3.

However when I launch pixelpulse,the correct version briefly greys out, and as it changes to the pixelpulse page, it tells me that no device is connected.
Any suggestions how I can fix this?

**Comment by kevinmehall** [comment]
What prints in the terminal when you run `./nonolith-connect` with a device plugged in? If you've set it up to run on boot, `sudo service nonolith-connect stop` to stop that copy so they don't conflict.

It's likely a permissions issue, and you'll need to set up udev rules to give permissions to access the device. See the udev instructions at https://github.com/nonolith/connect#linux.

**Comment by Kollensperger** [comment]
I should say I also placed a file with the following contents in /lib/udev.d as both files named 60-nonlith-connect.rules and nonolith-connect.udev (not sure which one as the debian folder had a different name than in the linux instructions) on ubuntu mate there was no udev.d folder but there is a udev folder, maybe place this there?

```
SUBSYSTEM=="usb", ATTR{idVendor}=="59e3", ATTR{idProduct}=="cee1", GROUP:="nonolithd", MODE="0666"
SUBSYSTEM=="usb", ATTR{idVendor}=="59e3", ATTR{idProduct}=="b003", GROUP:="nonolithd", MODE="0666"
SUBSYSTEM=="usb", ATTR{idVendor}=="59e3", ATTR{idProduct}=="bbbb", GROUP:="nonolithd", MODE="0666"
```

in addition I ran the following code from the nonolith-connect.postinst file in the debian folder:

```
mkdir -p /var/lib/nonolith-connect
addgroup --quiet --system nonolithd
adduser --quiet --system --ingroup nonolithd \
--home nonolithd --no-create-home nonolithd

chown nonolithd:nonolithd /var/lib/nonolith-connect
```

I think maybe this is where something went wrong?
If i do ''' sudo service nonolith-connect stop''' and then 
`cd connect
./nonolith-connect`
with the CEE plugged in, it returns 
`Could not open device; error -3
Error initializing new device. Ignoring.`

**Comment by kevinmehall** [comment]
Error `-3` [is](http://libusb.sourceforge.net/api-1.0/group__misc.html) LIBUSB_ERROR_ACCESS, so it is a permissions issue, and you'll have to find the right place for udev rules on your distribution. `sudo udevadm control --reload-rules` and re-plug the device to make the rules take effect.

**Comment by Kollensperger** [comment]
I just realised I started the thread on Rasbian and switched to ubuntu mate half way through.
In anycase I now got it working after placing the `60-nonlith-connect.rules` file 
in
`lib/udev/rules.d`
Thank you very much for your help, really appreciate it!
